### ISSUE TITLE
[2.3.56] Multiple holes in perimeter

### ISSUE THREAD

**Issue by zztopper** [supermerill/SuperSlicer#1172]
**Describe the bug**
Slicer leaves many holes in perimeter when slicing.

**To Reproduce**
Put a model on a plate and slice. 

**>> Project File <<**
[Motor_Frame_x1.3mf.zip](https://github.com/supermerill/SuperSlicer/files/6528815/Motor_Frame_x1.3mf.zip)

**Expected behavior**
No holes in perimeter after slicing the model

**Screenshots**
![unknown](https://user-images.githubusercontent.com/6938996/119274678-d1809000-bc19-11eb-9a45-fa4df7a2997e.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.3.1
 - Version 2.3.56.0

**Additional context**
Seems to be fixed if min extrusion length set to zero.

**Comment by supermerill** [comment]
can't reproduce

![image](https://user-images.githubusercontent.com/6536403/119402885-dc045d80-bcdd-11eb-91fd-f34967337af2.png)

if you load this project file, it does the thing you have in the picture?

**Comment by zztopper** [comment]
Hmm, not anymore, even if I set min extusion length back to 0.02, as it was before.
Can't reproduce either.
Some strange fluctuation, I guess you can close the issue

**Comment by supermerill** [comment]
Can't reproduce neither with some random old versions.
I fixed some errors from this feature in the last release.
If there is still some here, it's for me a big priority because everything go trough that.

**Comment by aka13-404** [comment]
![image](https://user-images.githubusercontent.com/51682059/120698228-0ceb4c00-c4af-11eb-9d94-8fe8a93abd21.png)
![image](https://user-images.githubusercontent.com/51682059/120698252-14125a00-c4af-11eb-81ae-72e02339d568.png)


The issue persists on the latest Nigthly windows x64 #333
Setting min extrude to 0 does not fix it.

**Comment by supermerill** [comment]
@aka13-404 
can you post your project file? can't reproduce without.

**Comment by aka13-404** [comment]
Just checked with stock configs, works good now. Must be something in the old configs, that breaks the slicing. 
Have attached the "broken" project files, but if it can not be reproduced with clean configs, 100% a config issue.

[Projects.zip](https://github.com/supermerill/SuperSlicer/files/6593812/Projects.zip)

**Comment by supermerill** [comment]
@aka13-404

the gcode viewer is freaking out because it lacks the start gcode that is hidden inside the klipper macro.
Have to do something to prevent that.

**Comment by aka13-404** [comment]
It's specifically the new "only custom Start G-Code" checkbbox, that is causing this, just checked.
The prescence of mm104 or m190 in the start gcode section does not do anything.

I will remain with the old bypass for now:
![image](https://user-images.githubusercontent.com/51682059/120707055-2219a800-c4ba-11eb-8ea6-294ac1a75c3b.png)
