### ISSUE TITLE
Multiple Extruders - Layer height cant be greater than nozzle diameter 

### ISSUE THREAD

**Issue by bung69** [supermerill/SuperSlicer#1233]
### Version
2.3.56.1

### Operating system type + version
win10

### Behavior
Layer height cant be greater than nozzle diameter Error seems to only compare layer height against the first extruder nozzle diameter. rather than the extruder in use for the print.   

Error is triggered with a layer height above 0.8mm  when all extrusion types are set to extruder 3 with 1.4mm Nozzle  and extruder 1 has a nozzle diameter of 0.8mm

[Layer height error.zip](https://github.com/supermerill/SuperSlicer/files/6589357/Layer.height.error.zip)
![Extruder 1](https://user-images.githubusercontent.com/55783483/120596753-066fbc80-c43c-11eb-84df-cd54e750bdec.PNG)
![Extruder 3](https://user-images.githubusercontent.com/55783483/120596776-0c659d80-c43c-11eb-9e55-47b6a399799c.PNG)
![Selected Extruder](https://user-images.githubusercontent.com/55783483/120596785-0f608e00-c43c-11eb-90c3-92760901547a.PNG)
![layer height](https://user-images.githubusercontent.com/55783483/120596788-1091bb00-c43c-11eb-84ea-8eeb8d848679.PNG)
![error](https://user-images.githubusercontent.com/55783483/120596794-125b7e80-c43c-11eb-84b0-3cbb2a4cf47b.PNG)

**Comment by supermerill** [comment]
can reproduce with 2.3.56.1 but not with the nigthly, should be fixed

**Comment by bung69** [comment]
oops might of attached wrong file in the OP.  

[Layer height error.zip](https://github.com/supermerill/SuperSlicer/files/6589625/Layer.height.error.zip)

Just checked on the nightly,  empty error box appears.  and invalid data button,  however slice now button appears after toggling a setting but still doesn't work.

It also looks like there are other bugs in the nightly, such as brim ears not working and the Gcode and sliced Previews being very slow / Chugging.

**Comment by supermerill** [comment]
> brim ears not working

i just fixed them, do you have a project for that bug?

**Comment by bung69** [comment]
Project attached. 

Nozzle size / max layer Hight appears to work correctly with multiple extruders now Thanks, 
Gcode and sliced previews interaction both work at a decent speed now too. 

Brim Ears still dosnt work 
Support is on top of  a raft even with interface layers and raft set to 0,  I forget if this is expected / desired or not but it overlaps the brim.  i usually use the work around of "solid first layer" 

[Brim Ears and Support Raft Error.zip](https://github.com/supermerill/SuperSlicer/files/6614135/Brim.Ears.and.Support.Raft.Error.zip)

**Comment by supermerill** [comment]
I see, the problem is that the brim ears are not generated around the support like the normal one.

**Comment by bung69** [comment]
![Brim_checked](https://user-images.githubusercontent.com/55783483/121295182-82f41680-c8e6-11eb-89d6-b1ab9df1d9d9.PNG)

![No Suport Interface Layers](https://user-images.githubusercontent.com/55783483/121295187-84bdda00-c8e6-11eb-9668-a73606789241.PNG)

![NoBrimAroundPart](https://user-images.githubusercontent.com/55783483/121295192-87203400-c8e6-11eb-8b9a-eb3bf0bb4d2e.PNG)


I get No Brim Ears at all,  on the part or the support.
