### ISSUE TITLE
Font size is unreadably small

### ISSUE THREAD

**Issue by jdblack** [supermerill/SuperSlicer#1698]
**Describe the bug**
The font size for the superslicer UI is too small for me to read and I wasn't able to find a way to increase the font size.

**To Reproduce**
1. Open up superslicer 2.3.67
2. Wait until you get to 50 years old

**Expected behavior**
An option under Configuration-> Preferences -> GUI to make the font  as large as 200-300%

**Screenshots**

![Screen Shot 2021-10-24 at 5 44 31 PM](https://user-images.githubusercontent.com/1109549/138619617-b664c2cc-c5f6-4943-8abc-1b82d2753f43.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.4 Big Sur
 - Version [e.g. 2.3.67
 

**Additional context**
This is literally the first time I've used superslicer or, for that matter, a slicer other than Cura.   I usually have to set a font size of around 24 to  read UIs.

**Comment by lucky62** [comment]
The same problem on Linux Mint.
![image](https://user-images.githubusercontent.com/16965519/142914675-defda75a-ed75-4b2a-b9f2-247bab2efaf8.png)

**Comment by neophyl** [comment]
I think this another one they have had with PS.  Might be worth checking what they did.
Sorry I currently dont have time to fins the issue numbers.  Busy at work :)

**Comment by supermerill** [comment]
btw, did you used teh linux appimage of the gtk2-appimage? is the problem only on one of them?

**Comment by lucky62** [comment]
> btw, @lucky62 did you used the linux appimage of the gtk2-appimage? is the problem only on one of them?

I didn't tried gtk2 version before..
Downloaded just now, and seems ok. 
I don't know which version I downloaded before, because I cannot find details..
File name was changed by AppImageLauncher and dialog "About" is showing the same info in both instances.
Both are the 2.3.57.6. No additional info.

Screenshot: Both instances running with open Preferences:

![image](https://user-images.githubusercontent.com/16965519/144378461-7b167323-5a7f-4768-980e-7027093d0605.png)

So, I will use the Gtk2 version and from my side the problem is solved. 
Thanks for help.

**Comment by supermerill** [comment]
I added a preference to override the os scaling factor, but you will still have the os scaling for the menus and dialogs.

**Comment by thisiscam** [comment]
Hi, I'm using the latest release on Mac and can't seem to find this option to scale font size?

**Comment by supermerill** [comment]
oups, seems like I nuked it by mistake, i'll re-add it in next nightly.

**Comment by timperlabs** [comment]
Just switching over to SuperSlicer from PS in hopes that the font size issue might be resolved here but I cannot find the configuration option under GUI.  I see only Tab Icon Size which doesn't seem to do much.   

I spent a few hours learning how to build the system though I know nothing about wxWidgets.  However, by brute force I bashed the font size mostly into submission by changing a few things including such as:

1) Change the default case to `return wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT).Scaled(1.3);` in GUI_Utils.cpp.
2) Adding `.Scaled(1.3)` to definition of `m_normal_font`, `m_bold_font`, ... in GUI_App.cpp
3) Adding `Scaled(1.3)` to various calls to `wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT)` throughout.  I am not sure why the code is littered with this anyway and not nicely factored out.

This seems to enlarge all fonts except for the ones on the left of the settings page next to the icons.  Those are very resistant.  This is important to me as I meet the OP's conditions and would like to continue using SuperSlicer when my RatRig arrives next month.   Please update on the status here and I'd be willing to help.  In my private build, you can see that most of the text is 30% larger now.


<img width="911" alt="Screen Shot 2022-05-05 at 5 52 38 PM" src="https://user-images.githubusercontent.com/7274670/167031697-07d99e29-9e32-408b-b721-a241452fd9f1.png">

**Comment by supermerill** [comment]
> Just switching over to SuperSlicer from PS in hopes that the font size issue might be resolved here but I cannot find the configuration option under GUI. I see only Tab Icon Size which doesn't seem to do much.

It's only in the latest nightlies (you can get them from the action menu):
![image](https://user-images.githubusercontent.com/6536403/167048687-79615be9-63f9-4130-acbe-e9586298f20d.png)

**Comment by timperlabs** [comment]
Thanks for the tip.  I tried the nightly dmg for last night and also for the one 3 days ago.  Both of them crashed on launch as follows.  

<img width="1080" alt="Screen Shot 2022-05-05 at 10 06 49 PM" src="https://user-images.githubusercontent.com/7274670/167055080-dd46d838-d582-4a3a-98d9-13bbc78f89a2.png">

Is the fix in Master or some other branch?   I can build from there as I've built successfully using the BuildMacOS.sh script.

**Comment by timperlabs** [comment]
I just tried the latest nightly Mac build again and it runs and shows the item in the Preferences box.  Changes to it are accepted and trigger a restart.  However, changing the value to 12, 15, 20 produces no change in font sizes and it still looks tiny.

**Comment by timperlabs** [comment]
This might already be obvious or be known but I want to point out that the code for getting fonts in `GUI_Utils.cpp` is rather suspicious and looks like someone coded it only caring about Windows.  The method is supposed to care about dpi but does all sorts of calculations only if it's Windows.  Otherwise, it simply throws away the argument and returns `wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT)` so it's not clear that the `DPIAware` template is going to help.

```
wxFont get_default_font_for_dpi(const wxWindow *window, int dpi)
{
#ifdef _WIN32
    // First try to load the font with the Windows 10 specific way.
    struct SystemParametersInfoForDpi_t { typedef BOOL (WINAPI *FN)(UINT uiAction, UINT uiParam, PVOID pvParam, UINT fWinIni, UINT dpi); };
    static auto SystemParametersInfoForDpi_fn = winapi_get_function<SystemParametersInfoForDpi_t>(L"User32.dll", "SystemParametersInfoForDpi");
    if (SystemParametersInfoForDpi_fn != nullptr) {
        NONCLIENTMETRICS nm;
        memset(&nm, 0, sizeof(NONCLIENTMETRICS));
        nm.cbSize = sizeof(NONCLIENTMETRICS);
        if (SystemParametersInfoForDpi_fn(SPI_GETNONCLIENTMETRICS, sizeof(NONCLIENTMETRICS), &nm, 0, dpi))
            return wxFont(wxNativeFontInfo(nm.lfMessageFont, window));
    }
    // Then try to guesstimate the font DPI scaling on Windows 8.
    // Let's hope that the font returned by the SystemParametersInfo(), which is used by wxWidgets internally, makes sense.
    int dpi_primary = get_dpi_for_window(nullptr);
    if (dpi_primary != dpi) {
        // Rescale the font.
        return wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT).Scaled(float(dpi) / float(dpi_primary));
    }
#endif
    return wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT);
}
```
