### ISSUE TITLE
Arachne still buggy in latest NB?

### ISSUE THREAD

**Issue by locki-cz** [supermerill/SuperSlicer#3206]
### What happened?

Arachne still shows some artefacts in latesin NB.
![image](https://user-images.githubusercontent.com/30490842/189638515-7b7339dd-c11a-48bb-a0a6-12d548ca50c6.png)

### Project file & How to reproduce

It shows only on this top part ... on rest of model it works fine ... 

### Version

2.5.59.0 NB

### Operating system

Win 10

### Printer model

Voron 2.4 SB

**Comment by zeroemso** [comment]
since it is arachne related i jump in here....found another reproducable bug.

at this part in the pic its just leaves a missing line on every 2nd layer. If i switch to classic its all normal (but Gap fill is used there)
![2022-09-12_16h28_57](https://user-images.githubusercontent.com/111010928/189680723-729b4189-e2f8-41d5-8b7e-75d5e0a3545f.jpg)
![2022-09-12_16h31_22](https://user-images.githubusercontent.com/111010928/189681203-e52d2747-f20d-460d-adaf-932a59e09221.jpg)

**Comment by supermerill** [comment]
@locki-cz your project?

**Comment by locki-cz** [comment]
[Hera_CQR_motor_cover-arachne.zip](https://github.com/supermerill/SuperSlicer/files/9551775/Hera_CQR_motor_cover-arachne.zip)
Sorry i forgot! :(

**Comment by ChaosBlades** [comment]
No Problems here on 2.5.590. I would revert to a stock slicing profile and try again.
![Screenshot from 2022-09-13 01-37-14](https://user-images.githubusercontent.com/7530545/189818031-3c5ed03a-21bd-4c39-bca1-51cba450ec40.png)

**Comment by ChaosBlades** [comment]
It is definitely enabled. Maybe it is either that I am using Linux or I have some setting that is causing the bug that is either disabled or changed in some way that is avoiding the issue.
![Screenshot from 2022-09-13 05-19-37](https://user-images.githubusercontent.com/7530545/189863685-45154669-46d4-4a3c-b4ce-f9bf533f7ee7.png)


[Hera_CQR_Stock_advanced-repaired-fixed.zip](https://github.com/supermerill/SuperSlicer/files/9555507/Hera_CQR_Stock_advanced-repaired-fixed.zip)

**Comment by supermerill** [comment]
fixed by prusa with the full 2.5 merge.

**Comment by locki-cz** [comment]
it looks same, that model is bad but why it doing this? :)

![image](https://user-images.githubusercontent.com/30490842/190015099-09848aa7-b52f-4b5e-a66a-4b5001e1ba4a.png)

**Comment by ChaosBlades** [comment]
Did a little more research and I found someone looking at the setting page for Arachne on SuperSlicer and it looks like it is bugged on Linux as I do not have that settings panel. I tried to remove both Stable and Arachne AppImage of SuperSlicer and reinstall. Also tried to create a new custom printer after that and the page still does not show up. I finally got it to show up by removing the .config folder. I don't know the situation on Windows/Mac but on Linux it appears anyone that updates and wants to use Arachne will need to start with a fresh install.
![Screenshot from 2022-09-13 18-55-23-2](https://user-images.githubusercontent.com/7530545/190023877-e80e96e4-45d2-4c93-ba83-eb44ff15f8a2.png)


Once I got the Arachne settings to show up I was able to reproduce the bug.

**Comment by supermerill** [comment]
> Did a little more research and I found someone looking at the setting page for Arachne on SuperSlicer

Check you're using the Configuration -> Preferences -> GUI -> Settings layout & colors -> STANDARD
and not the exemple.

**Comment by ChaosBlades** [comment]
I am using Standard.
![Screenshot from 2022-09-13 19-28-15](https://user-images.githubusercontent.com/7530545/190027172-e14c2880-2f3f-4551-b655-6cbdb8c52223.png)
I fixed the problem by deleting the `ui_layout` folder in the .config directory. It does not appear so far that I have lost any important settings. Looks like the last time that folder was modified was the 15th of July.

**Comment by pa0los** [comment]
I faced the same issue.
The workaround from @ChaosBlades worked for me as well.
Thanks!
