### ISSUE TITLE
How to set up first layer height on raft?

### ISSUE THREAD

**Issue by ZhenyaKa** [supermerill/SuperSlicer#685]
### Version
2.3.55

### Operating system type + version
Win7 x64

Slicing on table slicer uses first layer height option and all okay.
But when use raft I got 0.4 layer height of object on raft and can't ajust that height.

**Comment by supermerill** [comment]
fixed in 2.3.55.1

**Comment by brianredbeard** [comment]
@ZhenyaKa Out of curiosity, what is your nozzle diameter?

**Comment by ZhenyaKa** [comment]
> @ZhenyaKa Out of curiosity, what is your nozzle diameter?

0,4 and 0.6 I use

**Comment by liftbag** [comment]
I'm using the *2.3.55.3 fix error in Voron.ini update ender3 manual mmu C/C++ CI macos #192* (because I cannot use the newer versions. See #777) and seem to me that the issue isn't fixed yet.
From what I see, the raft-piece gap is exactly equal to the diameter of the nozzle + the offset set.
It would be, in my opinion, much more correct and easier to understand and set, that the raft-piece gap followed exactly the same logic used for the support-piece gap, namely layer height + offset.

**Comment by Limb** [comment]
Running 2.3.55.4 (commit a4699e7) and also seeing this issue. When setting any number of raft layers, the first layer of the model seems to be set to the nozzle diameter. With a 0.4 nozzle and 2 rafter layers, the first object layer is 0.4 as such:

![image](https://user-images.githubusercontent.com/240752/105789244-12101b80-5f50-11eb-805b-8b0aec5e5ce2.png)

All subsequent layers after this one are the correct 0.2mm height. For a 0.6 nozzle, first layer is 0.6:

![image](https://user-images.githubusercontent.com/240752/105789402-60251f00-5f50-11eb-9ab5-daad79184dc4.png)

Trying to adjust the layer height with adapter layers also shows it as 0.4 and blocked out in red as invariable.

![image](https://user-images.githubusercontent.com/240752/105789332-3ec43300-5f50-11eb-8bbd-245cf37397fa.png)

**Comment by supermerill** [comment]
of course, as there is no support to push through, the filament will be a cylinder and so the height will be the diameter of the nozzle (in theory). It may be a bit smaller with lower bridge flow, but I haven't tested it.

> It would be, in my opinion, much more correct and easier to understand and set, that the raft-piece gap followed exactly the same logic used for the support-piece gap, namely layer height + offset.

I agree.
Seems like prusa is rewriting the support code right now, so I'll wait for their 2.4 to touch it again.
